{
  "hash": "c137856dc49c43c12274717baeddd04c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"European Tech & Engineering Job Market Evolution\"\nsubtitle: \"A Data-Driven Analysis (2014-2024)\"\nauthor: \"kouki abderrahmen\"\ndate: today\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    toc-location: left\n    number-sections: true\n    code-fold: true\n    code-summary: \"Show code\"\n    theme: cosmo\n    self-contained: true\nexecute:\n  echo: false\n  warning: false\n  message: false\n---\n\n\n::: {.cell}\n\n:::\n\n\n# Introduction\n\n## Motivation\n\nThe European labor market has undergone significant transformation over the past decade, driven by digitalization and technological advancement. Understanding these changes is critical for policymakers, educators, and job seekers alike.\n\nThis report analyzes key indicators of the European tech and engineering job market from 2014 to 2024, using official Eurostat data to answer fundamental questions about workforce evolution, opportunity dynamics, and educational pipeline alignment.\n\n## Research Questions\n\nThis analysis addresses the following questions:\n\n1. **ICT Employment Growth**: How has the share of ICT specialists in total employment evolved across EU countries?\n\n2. **Labor Market Dynamics**: What is the relationship between unemployment and job vacancies (the Beveridge curve)?\n\n3. **Sectoral Opportunities**: How do job vacancy rates in the Information & Communication sector compare to the overall economy?\n\n4. **Educational Pipeline**: Are European universities producing enough ICT and engineering graduates to meet market demands?\n\n5. **Cross-Country Variation**: Which countries lead in ICT employment, and what factors correlate with higher tech employment shares?\n\n# Data Sources\n\nAll data are sourced from Eurostat, the statistical office of the European Union.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Eurostat Datasets Used in This Analysis\n\n|Indicator              |Dataset Code    |Description                                 |Coverage         |\n|:----------------------|:---------------|:-------------------------------------------|:----------------|\n|ICT Employment         |isoc_sks_itspt  |Employed ICT specialists as % of employment |2014-2024        |\n|Unemployment (Annual)  |une_rt_a        |Unemployment rate, ages 15-74               |2014-2024        |\n|Unemployment (Monthly) |une_rt_m        |Seasonally adjusted unemployment rate       |2020-2025        |\n|Job Vacancies          |jvs_a_rate_r2   |Job vacancy rate by NACE sector             |2014-2024        |\n|Graduates              |educ_uoe_grad02 |Tertiary graduates by field                 |2014-2023        |\n|Earnings               |earn_ses_pub2s  |Median hourly earnings (SES)                |2014, 2018, 2022 |\n\n\n:::\n:::\n\n\n## Geographic Coverage\n\nThe analysis covers:\n\n- **EU27**: European Union (27 member states, post-Brexit composition)\n- **Individual EU member states**: All 27 countries\n- **Associated countries**: UK, Switzerland, Norway, Iceland (where available)\n\n# Methodology\n\n## Data Pipeline\n\nThe analysis follows a reproducible pipeline:\n\n1. **Download**: Raw data fetched from Eurostat API using the `eurostat` R package\n2. **Clean**: Standardize formats, handle missing values, apply filters\n3. **Transform**: Create derived indicators, build panel dataset\n4. **Visualize**: Generate publication-quality figures\n5. **Report**: Compile findings in this document\n\n## Key Definitions\n\n- **ICT Specialists**: Workers whose main job involves developing, operating, and maintaining ICT systems (as defined by Eurostat)\n- **Job Vacancy Rate**: Number of job vacancies as a percentage of occupied posts plus vacancies\n- **NACE Sector J**: Information and Communication activities\n- **NACE Sector M**: Professional, Scientific, and Technical activities\n\n# Results\n\n## ICT Specialists Employment\n\n### EU27 Trend\n\n\n::: {.cell}\n\n:::\n\n\nThe share of ICT specialists in EU27 total employment has grown steadily over the past decade:\n\n- **Starting point (2014)**: 3.4% of total employment\n- **Latest data (2024)**: 5.0% of total employment\n- **Change**: +1.6 percentage points\n\n\n::: {.cell}\n::: {.cell-output-display}\n![ICT Specialists Share of Employment Over Time](../outputs/figures/fig01_ict_share_trend.png){#fig-ict-trend}\n:::\n:::\n\n\n### Cross-Country Comparison\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Top 10 Countries by ICT Employment Share, 2024\n\n|Country     | ICT Share (%)|\n|:-----------|-------------:|\n|Sweden      |           8.6|\n|Luxembourg  |           8.0|\n|Finland     |           7.8|\n|Estonia     |           7.2|\n|Netherlands |           7.0|\n|Ireland     |           6.3|\n|Denmark     |           5.8|\n|Belgium     |           5.7|\n|Switzerland |           5.7|\n|Norway      |           5.5|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![ICT Employment Share: Top and Bottom Countries](../outputs/figures/fig08_ict_share_ranking.png){#fig-ict-ranking}\n:::\n:::\n\n\n## Job Vacancy Dynamics\n\n### Information & Communication Sector\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Job Vacancy Rate in Information & Communication Sector](../outputs/figures/fig03_vacancy_rate_J_trend.png){#fig-vacancy-j}\n:::\n:::\n\n\nThe Information & Communication sector (NACE J) consistently shows higher vacancy rates than the overall economy, indicating persistent demand for workers in this field.\n\n### Beveridge Curve Analysis\n\nThe Beveridge curve shows the relationship between unemployment and job vacancies. A shift in this relationship can indicate structural changes in the labor market.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Beveridge Curve: EU27 Unemployment vs Job Vacancies](../outputs/figures/fig04_unemp_vs_vacancy.png){#fig-beveridge}\n:::\n:::\n\n\n## Educational Pipeline\n\n### Graduate Trends\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Tertiary Graduates in ICT and Engineering Fields](../outputs/figures/fig05_graduates_ict_vs_eng.png){#fig-graduates}\n:::\n:::\n\n\n## Earnings Relationship\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Relationship Between ICT Employment and Hourly Earnings](../outputs/figures/fig06_salary_vs_ict_share.png){#fig-salary}\n:::\n:::\n\n\nCountries with higher ICT employment shares tend to have higher median hourly earnings, though causality cannot be established from this cross-sectional relationship.\n\n## Work-Based Learning\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Exposure of VET Graduates to Work-Based Learning](../outputs/figures/fig07_wbl_exposure_bar.png){#fig-wbl}\n:::\n:::\n\n\n# Statistical Analysis\n\nThis section presents formal hypothesis testing to validate key patterns observed in the descriptive analysis. As a software engineering student analyzing this data, I'm particularly interested in whether these trends are statistically meaningful or could be due to chance.\n\n\n::: {.cell}\n\n:::\n\n\n## Time Trend Analysis\n\n**Research Question:** Has ICT employment share increased significantly over time?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View statistical test code\"}\n# Linear regression of ICT share on year\neu27_trend <- panel_stats |>\n  filter(geo == \"EU27_2020\", !is.na(ict_share_pc_emp))\n\nmodel_trend <- lm(ict_share_pc_emp ~ year, data = eu27_trend)\ntrend_summary <- broom::tidy(model_trend)\ntrend_fit <- broom::glance(model_trend)\n\nknitr::kable(\n  trend_summary,\n  digits = 4,\n  caption = \"Time Trend Regression Results\",\n  col.names = c(\"Term\", \"Estimate\", \"Std Error\", \"t-statistic\", \"p-value\")\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Time Trend Regression Results\n\n|Term        |  Estimate| Std Error| t-statistic| p-value|\n|:-----------|---------:|---------:|-----------:|-------:|\n|(Intercept) | -331.7791|   16.3139|    -20.3372|       0|\n|year        |    0.1664|    0.0081|     20.5891|       0|\n\n\n:::\n:::\n\n\n**Interpretation:** The ICT employment share increases by approximately **0.166 percentage points per year** (p < 0.001). This is highly statistically significant, meaning the growth pattern isn't random—it's a real trend. From a software developer's perspective, this confirms what we see in the job market: tech roles are consistently growing as a share of total employment.\n\n**Key Insight:** With an R² of 0.979, the year alone explains about 98% of the variation in ICT employment. This linear trend has been remarkably consistent over the decade.\n\n## Vacancy Rate Comparison\n\n**Research Question:** Do tech sector vacancy rates exceed overall economy rates?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View test code\"}\nvacancy_data <- panel_stats |>\n  filter(!is.na(vacancy_rate_J), !is.na(vacancy_rate_total))\n\nif (nrow(vacancy_data) > 10) {\n  vacancy_test <- t.test(\n    vacancy_data$vacancy_rate_J,\n    vacancy_data$vacancy_rate_total,\n    paired = TRUE\n  )\n  \n  vacancy_result <- broom::tidy(vacancy_test)\n  \n  knitr::kable(\n    vacancy_result |> select(estimate, statistic, p.value, conf.low, conf.high),\n    digits = 3,\n    caption = \"Paired t-test: Tech Sector vs Overall Economy Vacancy Rates\",\n    col.names = c(\"Mean Difference (%)\", \"t-statistic\", \"p-value\", \"95% CI Low\", \"95% CI High\")\n  )\n} else {\n  cat(\"*Note: Insufficient data available for vacancy rate comparison due to Eurostat API limitations.*\")\n}\n```\n\n::: {.cell-output-display}\n\n\nTable: Paired t-test: Tech Sector vs Overall Economy Vacancy Rates\n\n| Mean Difference (%)| t-statistic| p-value| 95% CI Low| 95% CI High|\n|-------------------:|-----------:|-------:|----------:|-----------:|\n|               0.791|       17.23|       0|      0.701|       0.882|\n\n\n:::\n:::\n\n\n\n**Interpretation:** Tech sector vacancy rates are **0.79% higher** than the overall economy (p < 0.001). This confirms what many of us in software engineering experience: companies struggle more to fill tech positions compared to other roles. The persistent talent gap means job security and negotiating power for developers.\n\n## Earnings-ICT Employment Correlation\n\n**Research Question:** Do countries with higher ICT employment have higher earnings?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View correlation test\"}\nearnings_data <- panel_stats |>\n  filter(!is.na(median_hourly_earnings_eur), !is.na(ict_share_pc_emp))\n\nif (nrow(earnings_data) > 10) {\n  cor_test <- cor.test(\n    earnings_data$ict_share_pc_emp,\n    earnings_data$median_hourly_earnings_eur,\n    method = \"pearson\"\n  )\n  \n  cor_result <- broom::tidy(cor_test)\n  \n  knitr::kable(\n    cor_result |> select(estimate, statistic, p.value, conf.low, conf.high),\n    digits = 3,\n    caption = \"Pearson Correlation: ICT Employment Share vs Median Earnings\",\n    col.names = c(\"Correlation (r)\", \"t-statistic\", \"p-value\", \"95% CI Low\", \"95% CI High\")\n  )\n}\n```\n\n::: {.cell-output-display}\n\n\nTable: Pearson Correlation: ICT Employment Share vs Median Earnings\n\n| Correlation (r)| t-statistic| p-value| 95% CI Low| 95% CI High|\n|---------------:|-----------:|-------:|----------:|-----------:|\n|           0.628|        7.78|       0|      0.488|       0.736|\n\n\n:::\n:::\n\n\n\n**Interpretation:** There's a **strong positive correlation** (r = 0.628, p < 0.001) between ICT employment share and median earnings. About 39% of the variation in earnings across countries can be explained by ICT employment levels. As someone studying software engineering, this is encouraging—countries investing in tech sectors tend to have better overall wage levels. However, correlation doesn't prove causation; it could be that wealthier countries both pay more AND have more tech jobs.\n\n## Beveridge Curve Relationship\n\n**Research Question:** Are unemployment and vacancy rates negatively correlated?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nbeveridge_data <- panel_stats |>\n  filter(geo == \"EU27_2020\", !is.na(unemp_rate_pc_act), !is.na(vacancy_rate_total))\n\nif (nrow(beveridge_data) > 5) {\n  beveridge_cor <- cor.test(\n    beveridge_data$unemp_rate_pc_act,\n    beveridge_data$vacancy_rate_total,\n    method = \"pearson\"\n  )\n  \n  beveridge_result <- broom::tidy(beveridge_cor)\n  \n  knitr::kable(\n    beveridge_result |> select(estimate, statistic, p.value),\n    digits = 3,\n    caption = \"Beveridge Curve Correlation (EU27)\",\n    col.names = c(\"Correlation (r)\", \"t-statistic\", \"p-value\")\n  )\n}\n```\n\n::: {.cell-output-display}\n\n\nTable: Beveridge Curve Correlation (EU27)\n\n| Correlation (r)| t-statistic| p-value|\n|---------------:|-----------:|-------:|\n|           -0.95|      -9.105|       0|\n\n\n:::\n:::\n\n\n\n**Interpretation:** The **negative correlation** (r = -0.950, p = 0.000) confirms the classic Beveridge curve relationship: when unemployment is low, vacancies are high, and vice versa. From a job seeker's perspective, this means during economic expansions (low unemployment), there are more open positions available. The relationship isn't perfect because structural factors also matter—skills mismatches can cause high unemployment and high vacancies simultaneously.\n\n## COVID-19 Structural Break Analysis\n\n**Research Question:** Did COVID-19 cause a measurable acceleration in ICT employment growth?\n\nThe pandemic of 2020 dramatically accelerated digital transformation across Europe. We test whether this represents a statistically significant \"structural break\" in the ICT employment trend.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"View structural break test code\"}\n# Structural break test: interaction between time and COVID period\neu27_covid <- panel_stats |>\n  filter(geo == \"EU27_2020\", !is.na(ict_share_pc_emp)) |>\n  mutate(covid = ifelse(year >= 2020, 1, 0))\n\nif (nrow(eu27_covid) > 5) {\n  model_break <- lm(ict_share_pc_emp ~ year * covid, data = eu27_covid)\n  break_summary <- broom::tidy(model_break)\n  \n  knitr::kable(\n    break_summary,\n    digits = 4,\n    caption = \"Structural Break Regression: COVID-19 Impact on ICT Growth\",\n    col.names = c(\"Term\", \"Estimate\", \"Std Error\", \"t-statistic\", \"p-value\")\n  )\n}\n```\n\n::: {.cell-output-display}\n\n\nTable: Structural Break Regression: COVID-19 Impact on ICT Growth\n\n|Term        |  Estimate| Std Error| t-statistic| p-value|\n|:-----------|---------:|---------:|-----------:|-------:|\n|(Intercept) | -226.7905|   16.0515|    -14.1290|  0.0000|\n|year        |    0.1143|    0.0080|     14.3574|  0.0000|\n|covid       | -112.3095|   26.6646|     -4.2119|  0.0040|\n|year:covid  |    0.0557|    0.0132|      4.2207|  0.0039|\n\n\n:::\n:::\n\n\n\n**Interpretation:** The interaction term (year × covid) is **statistically significant** (p = 0.0039), indicating that COVID-19 caused a genuine acceleration in ICT employment growth. The slope increased by approximately **0.0557 percentage points per year** after 2020. This confirms what many of us experienced—the pandemic didn't just temporarily shift work online, it fundamentally accelerated the structural growth of tech employment in Europe.\n\n## Statistical Summary\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n*Note: *** indicates p < 0.05 (statistically significant), ns = not significant*\n```\n\n\n:::\n:::\n\n\n**Bottom Line:** The statistical tests confirm what the visualizations suggest: ICT employment is genuinely growing, tech sector demand exceeds overall economy demand, and countries with more tech jobs tend to have higher earnings. These aren't just visual patterns—they're statistically robust findings that can inform career and policy decisions.\n\n::: {.callout-note}\n## 📊 Key Statistical Conclusions\n\nAll tests show **highly significant results** (p < 0.05), confirming that:\n\n1. ✅ **ICT employment is genuinely growing** (not random) — Linear regression shows consistent +0.166 pp/year growth with R² = 0.98\n\n2. ✅ **Tech sector has persistently higher vacancy rates** — Paired t-test confirms tech vacancies exceed overall economy by ~0.8%\n\n3. ✅ **Countries with more tech jobs have higher overall wages** — Pearson correlation r = 0.63 (strong positive relationship)\n\n4. ✅ **Standard labor market dynamics apply (Beveridge curve)** — Classic inverse relationship confirmed (r = -0.95)\n\n5. ✅ **COVID-19 caused a measurable acceleration in ICT growth** — Structural break test shows +0.056 pp/year additional growth post-2020 (p = 0.004)\n\n**Implication:** These findings provide robust statistical evidence supporting continued investment in digital skills and tech sector development across the EU.\n:::\n\n# Discussion\n\n## Key Findings\n\n1. **Growing ICT workforce**: The EU27 has seen consistent growth in ICT specialist employment, reflecting ongoing digitalization.\n\n2. **Persistent tech vacancies**: High vacancy rates in the Information & Communication sector suggest continued talent shortages.\n\n3. **Country heterogeneity**: Significant variation exists across EU countries in ICT employment shares, with Nordic and Western European countries generally leading.\n\n4. **Education-market alignment**: Graduate numbers in ICT fields have been increasing, but the relationship with labor market outcomes varies by country.\n\n## Limitations\n\n1. **Data availability**: Some indicators (especially earnings) are only available for select years.\n\n2. **Definition changes**: Eurostat methodological changes can affect time series comparability.\n\n3. **Aggregation issues**: EU27 aggregates may mask significant within-country variation.\n\n4. **Causality**: Cross-sectional correlations do not establish causal relationships.\n\n## Policy Implications\n\n- Investment in digital skills education appears well-justified given persistent vacancies\n- Countries with lower ICT employment shares may benefit from policies promoting digital transformation\n- Work-based learning programs may help bridge the gap between education and employment\n\n# Appendix\n\n## Session Information\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.3.3 (2024-02-29)\nPlatform: x86_64-conda-linux-gnu (64-bit)\nRunning under: Ubuntu 25.10\n\nMatrix products: default\nBLAS/LAPACK: /home/core/miniconda3/envs/statistical-analysis/lib/libopenblasp-r0.3.30.so;  LAPACK version 3.12.0\n\nlocale:\n [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              \n [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    \n [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   \n [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 \n [9] LC_ADDRESS=C               LC_TELEPHONE=C            \n[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       \n\ntime zone: Africa/Tunis\ntzcode source: system (glibc)\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] broom_1.0.11    scales_1.4.0    knitr_1.50      here_1.0.1     \n [5] lubridate_1.9.4 forcats_1.0.0   stringr_1.5.2   dplyr_1.1.4    \n [9] purrr_1.1.0     readr_2.1.5     tidyr_1.3.1     tibble_3.3.0   \n[13] ggplot2_3.5.2   tidyverse_2.0.0\n\nloaded via a namespace (and not attached):\n [1] gtable_0.3.6       jsonlite_2.0.0     compiler_4.3.3     tidyselect_1.2.1  \n [5] yaml_2.3.10        fastmap_1.2.0      R6_2.6.1           generics_0.1.4    \n [9] backports_1.5.0    rprojroot_2.1.1    pillar_1.11.0      RColorBrewer_1.1-3\n[13] tzdb_0.5.0         rlang_1.1.6        stringi_1.8.7      xfun_0.53         \n[17] timechange_0.3.0   cli_3.6.5          withr_3.0.2        magrittr_2.0.3    \n[21] digest_0.6.37      grid_4.3.3         hms_1.1.3          lifecycle_1.0.4   \n[25] vctrs_0.6.5        evaluate_1.0.5     glue_1.8.0         farver_2.1.2      \n[29] rmarkdown_2.29     tools_4.3.3        pkgconfig_2.0.3    htmltools_0.5.8.1 \n```\n\n\n:::\n:::\n\n\n## Data Dictionary\n\nSee `outputs/tables/data_dictionary.md` for full variable definitions.\n\n## Attribution\n\n**Data Source**: Eurostat (https://ec.europa.eu/eurostat)\n\nAll data are subject to Eurostat copyright policy. Reuse is authorized provided the source is acknowledged.\n\nDataset codes used: `isoc_sks_itspt`, `une_rt_a`, `une_rt_m`, `jvs_a_rate_r2`, `educ_uoe_grad02`, `earn_ses_pub2s`\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}